# Ref: https://docs.docker.com/build/ci/github-actions/
name: Build Docker Images

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/build.yaml
      - thirdparty/**
      - Dockerfile
      - .dockerignore

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        # Ref: https://github.com/docker/metadata-action
        uses: docker/metadata-action@v5
        with:
          # Link: https://hub.docker.com/repository/docker/j3soon/ros2-template-ws/tags
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ros-noetic-zed
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
